#!/bin/sh
# Start/stop the servergpio daemon.
#
### BEGIN INIT INFO
# Provides:          servergpio
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Regular background program processing daemon
# Description:       start xmlrpc server for remote GPIO management 

### END INIT INFO


. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="xmlrpc GPIO daemon"
NAME=servergpio
SCRIPT=/srv/xmlrpc/servergpio.py
DAEMON='/srv/xmlrpc/servergpio.py &'
PIDFILE=/var/run/servergpio.pid
SCRIPTNAME=/etc/init.d/"$NAME"
RUNAS1=root

test -f $SCRIPT || exit 0




case "$1" in
    start)

        log_daemon_msg "Starting $DESC" $NAME
        start-stop-daemon --start --oknodo --quiet \
            -b -m --pidfile $PIDFILE --exec $DAEMON
        
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" $NAME
        if start-stop-daemon --stop --retry 30 --oknodo --quiet \
            --pidfile $PIDFILE --exec $SCRIPT
        then
	    PID=`cat $PIDFILE | head -1`
	    kill -9 $PID
            rm -f $PIDFILE
            log_end_msg $?
        else
            log_end_msg $?
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0

